/** 
 * 0 - THE FOOL
 * 1 - THE MAGICIAN
 * 2 - THE HIGH PREISTESS
 * 3 - THE EMPRESS
 * 4 - THE EMPEROR
 * 5 - THE HEIROPHANT
 * 6 - THE LOVERS
 * 7 - THE CHARIOT
 * 8 - STRENGTH
 * 9 - THE HERMIT
 * 10 - WHEEL OF FORTUNE
 * 11 - JUSTICE
 * 12 - THE HANGED MAN
 * 13 - DEATH
 * 14 - TEMPERANCE
 * 15 - THE DEVIL
 * 16 - THE TOWER
 * 17 - THE STAR
 * 18 - THE MOON
 * 19 - THE SUN
 * 20 - JUDGMENT
 * 21 - THE WORLD
 * ACE OF WANDS
TWO OF WANDS
THREE OF WANDS
FOUR OF WANDS
FIVE OF WANDS
SIX OF WANDS
SEVEN OF WANDS
EIGHT OF WANDS
NINE OF WANDS
TEN OF WANDS
PAGE OF WANDS
KNIGHT OF WANDS
QUEEN OF WANDS
KING OF WANDS
ACE OF CUPS
TWO OF CUPS
THREE OF CUPS
FOUR OF CUPS
FIVE OF CUPS
SIX OF CUPS
SEVEN OF CUPS
EIGHT OF CUPS
NINE OF CUPS
TEN OF CUPS
PAGE OF CUPS
KNIGHT OF CUPS
QUEEN OF CUPS
KING OF CUPS
ACE OF SWORDS
TWO OF SWORDS
THREE OF SWORDS
FOUR OF SWORDS
FIVE OF SWORDS
SIX OF SWORDS
SEVEN OF SWORDS
EIGHT OF SWORDS
NINE OF SWORDS
TEN OF SWORDS
PAGE OF SWORDS
KNIGHT OF SWORDS
QUEEN OF SWORDS
KING OF SWORDS
ACE OF PENTACLES
TWO OF PENTACLES
THREE OF PENTACLES
FOUR OF PENTACLES
FIVE OF PENTACLES
SIX OF PENTACLES
SEVEN OF PENTACLES
EIGHT OF PENTACLES
NINE OF PENTACLES
TEN OF PENTACLES
PAGE OF PENTACLES
KNIGHT OF PENTACLES
QUEEN OF PENTACLES
KING OF PENTACLES
*/